---
# Need to enclose few of the below dependencies within quotes as the cmd string
# will be formed with spaces and pip install will fail without the quotes.
Default:
 python3-psutil
 'python3-tomli (>= 1.1.0)'
 'python3-tomli-w (>= 0.4.0)'
 meson